version: '3.0'

services: 
  frontend:
    restart: unless-stopped
    build: ./frontend
    image: registry.xnopyt.com/xnoeblog-frontend:latest
  
  backend:
    restart: unless-stopped
    build: ./backend
    image: registry.xnopyt.com/xnoeblog-backend:latest
    depends_on: 
      - database
    environment:
      - XNOEBLOG_USER=user
      - XNOEBLOG_PASS=password
  
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    restart: unless-stopped
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=xnoeblog
    volumes:
      - postgres:/var/lib/postgres/data

volumes:
  postgres: