version: '3.0'

services: 
  frontend:
    build: ./frontend
  
  backend:
    build: ./backend
  
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  database:
    image: postgres
    restart: unless-stopped
    environment: 
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=blog